### YamlMime:Lifecycle
metadata:
  title: Агент розгортання Microsoft 2013
  description: Корпорація Майкрософт розгортання агента 2013, слід фіксована політика життєвого циклу.
  ms.date: 07/28/2020
  ms.openlocfilehash: d81680178f3fc6d72450bbf62cbf11ccb7ef8dc5
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: uk-UA
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "865505"
name: Агент розгортання Microsoft 2013
summary: >+
  Корпорація Майкрософт розгортання агента 2013, слід [фіксована](/lifecycle/policies/fixed) політика життєвого циклу.


products:
- vs
policyType: fixed
supportDates:
  start: 01/15/2014
  end: 04/09/2019
  extendedEnd: 04/09/2024
releases:
- version: Original Release
  startDate: 01/15/2014
  endDate: 04/09/2024
content: "\n\n> [!NOTE]\n> Для розгортання агента 2013 оновлення 4 буде підтримуватись за правилами політики до 4/9/2024."
