### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 5.1
  description: До Microsoft Application Virtualization 5.1 застосовується політика фіксованого життєвого циклу.
  ms.date: 07/28/2020
  ms.openlocfilehash: 3f0cac2ee013dd73e44fe41d9ba1d07cfcfce2f1
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: HT
  ms.contentlocale: uk-UA
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "865514"
name: Microsoft Application Virtualization 5.1
summary: >+
  До Microsoft Application Virtualization 5.1 застосовується політика [фіксованого](/lifecycle/policies/fixed) життєвого циклу.


  Це стосується таких версій: for Remote Desktop Services (для служб віддалених робочих столів), for Windows Desktops (для робочих столів з Windows)

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Original Release
  startDate: 11/01/2015
  endDate: 04/14/2026
content: "\n## <a name=\"links\"></a>Посилання \n* [Інформація про продукт](/microsoft-desktop-optimization-pack/appv-v5/microsoft-application-virtualization-50-administrators-guide)\n\n\n## <a name=\"editions\"></a>Версії \n* для служб віддалених робочих столів\n* для Windows для настільних ПК"
