### YamlMime:Lifecycle
metadata:
  title: Microsoft Application віртуалізації хостинг 4,6 для настільних комп'ютерів Windows
  description: Microsoft Application Virtualization Hosting для настільних комп'ютерів під управлінням Windows керується фіксованою політикою життєвого циклу.
  ms.date: 07/28/2020
  ms.openlocfilehash: 21ed557cd6333e43a274796a3b25791c0d7f96cd
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: HT
  ms.contentlocale: uk-UA
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "845832"
name: Microsoft Application віртуалізації хостинг 4,6 для настільних комп'ютерів Windows
summary: >+
  Microsoft Application Virtualization Hosting 4.6 для настільних комп'ютерів під управлінням Windows керується [фіксованою](/lifecycle/policies/fixed) політикою життєвого циклу.


  Це стосується наступних випусків: Windows Desktops

products:
- windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
- version: Service Pack 3
  startDate: 12/02/2013
  endDate: 07/14/2020
- version: Service Pack 2
  startDate: 10/01/2012
  endDate: 01/13/2015
- version: Service Pack 1
  startDate: 01/26/2011
  endDate: 10/08/2013
- version: Original Release
  startDate: 05/27/2010
  endDate: 04/10/2012
content: "\n## <a name=\"links\"></a>Посилання \n* [Інформація про виріб та міграцію](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Політика пакетів оновлень](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Оскільки клієнт App-V 4.6 використовує сервер App-V 4.5, підтримка сервера App-V 4.5 буде продовжуватися відповідно до дат життєвого циклу App-V 4.6 у разі його використання з підтримуваним клієнтом App-V 4.6.\n\n## <a name=\"editions\"></a>Версії \n* для Windows для настільних ПК"
