### YamlMime:Lifecycle
metadata:
  title: Диспетчер конфігурацій Microsoft System Center 2012
  description: Диспетчер конфігурацій Microsoft System Center 2012 керується фіксованою політикою життєвого циклу.
  ms.date: 03/12/2021
  keywords: 
  ms.openlocfilehash: f710122044be40b9cbaf957f7c6ca06ea520fbd0
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: uk-UA
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4112616"
name: Диспетчер конфігурацій Microsoft System Center 2012
summary: >+
  Диспетчер конфігурацій Microsoft System Center 2012 керується [фіксованою](/lifecycle/policies/fixed) політикою життєвого циклу.


products:
- msc
policyType: fixed
supportDates:
  start: 2012-05-30T00:00:00.000-08:00
  end: 2017-07-11T22:59:59.999-08:00
  extendedEnd: 2022-07-12T22:59:59.999-08:00
releases:
- version: Service Pack 2
  startDate: 2015-05-12T00:00:00.000-08:00
  endDate: 2022-07-12T22:59:59.999-08:00
- version: Service Pack 1
  startDate: 2012-12-15T00:00:00.000-08:00
  endDate: 2016-07-12T22:59:59.999-08:00
- version: Original Release
  startDate: 2012-05-30T00:00:00.000-08:00
  endDate: 2014-01-14T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Посилання \n* [Політика пакетів оновлень](/lifecycle/policies/fixed#service-packs)\n* [Документація System Center](/system-center/#pivot=components&panel=components-all)\n* [Ресурси System Center](https://www.microsoft.com/system-center/resources)\n* [Вказівки щодо міграції](https://techcommunity.microsoft.com/t5/configuration-manager-blog/system-center-2012-configuration-manager-is-approaching-end-of/ba-p/1650899)"
